### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by AaronChuh** [UMass-Embodied-AGI/HAZARD#12]
Hi, thanks for your great work!

You mentioned in paper that a dataset was generated for the SAR task. Do you mean the roomsetup files in `src/HAZARD/data` which is used to build the task? 

And at the end of the paper I also find that you provide demonstrations on training set to train imitation learning models. However, I can't find the access to the dataset. Maybe I miss something here? Or could you explain how to generate such a dataset?

I would appreciate your help!

**Comment by zhouqqhh** [comment]
For the first question: Yes, the datasets are the roomsetup files.

For the second question, I will update the access to training decisions this week. They are generated from searching algorithm given the ground truth information

**Comment by zhouqqhh** [comment]
Hi,
You can run oracle agent by passing "oracle" in agent parameter and run experiments on the training set. The actions and observations in the output folder will be the training data.
Sorry that we do not have a spare machine today. If you want to, we can generate these data later.

Best,
Qinhong

**Comment by AaronChuh** [comment]
> Hi, You can run oracle agent by passing "oracle" in agent parameter and run experiments on the training set. The actions and observations in the output folder will be the training data. Sorry that we do not have a spare machine today. If you want to, we can generate these data later.

Thanks for your prompt reply!

I think I can generate data on my own. And I have another question here. 

Is it possible to save the environment’s intermediate states during an episode and restore to a specific time step later？ Specifically, I’d like to explore different decision-making strategies by returning to certain time steps and testing alternative actions from there.

**Comment by zhouqqhh** [comment]
I think TDW can recover any state from a log.txt file 
https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/read_write/logger.md

**Comment by AaronChuh** [comment]
> I think TDW can recover any state from a log.txt file https://github.com/threedworld-mit/tdw/blob/master/Documentation/lessons/read_write/logger.md

Hi, I execute code `submit(output_dir="outputs/", env_name="fire", agent="oracle", port=1071, max_test_episode=1, record_with_agents=True)` and find the agent didn't move at all. Here is log file.

[log.txt](https://github.com/user-attachments/files/19885808/log.txt)

**Comment by AaronChuh** [comment]
@zhouqqhh Hi, just following up on this issue. Would you mind taking a look when you have some time? Thanks a lot for your help!

**Comment by zhouqqhh** [comment]
Hi,
Sorry for the late reply. I found that it was because the oracle agent exits when it reaches the max search depth (we add this to avoid it taking too long). I have pushed a new version of oracle agent that will return a result even if it exceeds the maximum depth. You can try it again. Thanks!

**Comment by AaronChuh** [comment]
> Hi, Sorry for the late reply. I found that it was because the oracle agent exits when it reaches the max search depth (we add this to avoid it taking too long). I have pushed a new version of oracle agent that will return a result even if it exceeds the maximum depth. You can try it again. Thanks!

Hi, thanks for your update! I pull the latest code but still encounter the same issue. The log file is provided below.

[log.txt](https://github.com/user-attachments/files/19933152/log.txt)

By the way, there is a small mistake in the current repo -- an import error in `run_experiments.py` in line 14: `from policy.oracal import OracleAgent`, which should be `from policy.oracle import OracleAgent`.

**Comment by zhouqqhh** [comment]
Did you wait until the program ends? It will perform searching after simulation ends. In my test case, it outputs
`[["walk_to", 14640280], ["walk_to", 14544403], ["walk_to", 16728828], ["walk_to", 16381463], ["walk_to", 10511794], ["walk_to", 10844722], ["walk_to", 473176], ["walk_to", 474390], ["walk_to", 16013534], ["walk_to", 6999109], ["walk_to", 6798686]]`
in action-0.json

**Comment by AaronChuh** [comment]
> Did you wait until the program ends? It will perform searching after simulation ends. In my test case, it outputs `[["walk_to", 14640280], ["walk_to", 14544403], ["walk_to", 16728828], ["walk_to", 16381463], ["walk_to", 10511794], ["walk_to", 10844722], ["walk_to", 473176], ["walk_to", 474390], ["walk_to", 16013534], ["walk_to", 6999109], ["walk_to", 6798686]]` in action-0.json

Yes, I did wait until the tdw windows closed automatically and it was reported in terminal that
`2025-04-28 10:08:09,363 - fire_oracle_04/28/2025, 09:59:47 - INFO - eval done, avg score 0.0, max score 19.0, avg steps 1500.0
2025-04-28 10:08:09,363 - fire_oracle_04/28/2025, 09:59:47 - INFO - time: 501.82803416252136`

Here is the total outputs files including recorded images.

[outputs](https://drive.google.com/file/d/1cfuCVK9VQkE2yBXkfe26iOumfOO6_XMn/view?usp=sharing)
